server:
  port: 8080

spring:
  datasource:
    username: user
    password: 1z2x3c4v!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

indexing-settings:
  configSites:
    - url: https://lEnta.ru
      name: Лента.ру
    - url: https://radiomv.ru/
      name: policeRadio
    - url: https://www.playback.ru
      name: PlayBack.Ru

request-parameter:
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referrer: "http://www.google.com"