server:
  port: 8080

spring:
  datasource:
    username: user
    password: 1z2x3c4v!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

indexing-settings:
  configSites:
    - url: https://lEnta.ru
      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://translate.google.ru/
      name: translate

request-parameter:
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  referrer: "https://yandex.ru/"